{
    'name': 'Custom Website',
    'version': '1.0',
    'category': 'Website',
    'summary': 'A custom website module with external API call',
    'description': 'This module demonstrates how to call an external API using JS.',
    'author': 'Name',
    'depends': ['web', 'website', 'mail', 'stock_barcode', 'planning'],
    'data': [
        'wizard/assign_driver_views.xml',
        # 'views/custom_template.xml',
        'data/provinces.xml',
        'data/stock_warehouse.xml',
        'data/ir_cron.xml',
        # 'data/update_picking_types.xml',
        'views/res_users_views.xml',
        'views/hr_employee_views.xml',
        'views/shipping_zone_views.xml',
        'views/shipping_order_views.xml',
        'views/shipping_order_transport_views.xml',
        'views/leaflet_widget_view.xml',
        'views/custom_login.xml',
        'views/custom_signup.xml',
        'views/shipping_dashboard_views.xml',
        'views/shipping_dashboard.xml',
        'data/template_verification_email.xml',
        'data/template_fail_login_email.xml',
        'data/order_pdf.xml',
        # 'views/auth_signup_template.xml',
        # 'views/custom_template.xml',
        'security/ir.model.access.csv',
    ],
    'qweb': [],
    'assets': {
        'web.assets_frontend': [
            'custom_website/static/src/js/custom_script.js',
            'custom_website/static/src/js/custom_signup.js',
            'custom_website/static/src/css/custom_styles.css',
        ],
        'web.assets_backend': [
            'https://unpkg.com/leaflet@1.9.3/dist/leaflet.css',
            'https://unpkg.com/leaflet@1.9.3/dist/leaflet.js',
            'https://unpkg.com/leaflet-routing-machine/dist/leaflet-routing-machine.js',
            "https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.css",
            'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js',
            'custom_website/static/src/js/leaflet_map.js',
            'custom_website/static/src/xml/leaflet_map_widget.xml',
            'custom_website/static/src/css/drivers_map*',
            'custom_website/static/src/js/drivers_map*',
            'custom_website/static/src/xml/drivers_map*',
            'custom_website/static/src/js/zone_picker_widget.js',
            'custom_website/static/src/xml/zone_picker_widget.xml',
            'custom_website/static/src/components/**/*.js',
            'custom_website/static/src/components/**/*.xml',
            # 'custom_website/static/src/components/**/*.scss',
        ],
    },
    'post_init_hook': '_elog_post_init',
    'installable': True,
    'application': True,
}